'use strict';

var GRADE_POINTS_SIGNUP = 10;
var GRADE_POINTS_DOB = 5;
var GRADE_POINTS_NAME = 5;
var GRADE_POINTS_LOCATION = 5;
var GRADE_POINTS_VERIFIED_LOCATION = 20;
var GRADE_POINTS_THIRD_PARTY_SIGNUP = 20;
var GRADE_POINTS_VERIFIED_DOB = 5;
var GRADE_POINTS_CREDIT_CARD = 60;

var LOGIN_TYPE_GOOGLE = "GOOGLE";
var LOGIN_TYPE_FACEBOOK = "FACEBOOK";

var VERIFIED = "VERIFIED";
var UNABLE_TO_VERIFY = "Unable to verify";


module.exports = {
    GRADE_POINTS_SIGNUP: GRADE_POINTS_SIGNUP,
    GRADE_POINTS_DOB: GRADE_POINTS_DOB,
    GRADE_POINTS_NAME: GRADE_POINTS_NAME,
    GRADE_POINTS_LOCATION: GRADE_POINTS_LOCATION,
    GRADE_POINTS_VERIFIED_LOCATION: GRADE_POINTS_VERIFIED_LOCATION,
    GRADE_POINTS_THIRD_PARTY_SIGNUP: GRADE_POINTS_THIRD_PARTY_SIGNUP,
    GRADE_POINTS_VERIFIED_DOB: GRADE_POINTS_VERIFIED_DOB,
    GRADE_POINTS_CREDIT_CARD: GRADE_POINTS_CREDIT_CARD,
    LOGIN_TYPE_GOOGLE: LOGIN_TYPE_GOOGLE,
    LOGIN_TYPE_FACEBOOK: LOGIN_TYPE_FACEBOOK,
    VERIFIED: VERIFIED,
    UNABLE_TO_VERIFY: UNABLE_TO_VERIFY
};