module.exports = {
    Admins : require('./Admins'),
    AdminMargin : require('./AdminMargin'),
    fanspickUser : require('./fanspickUser'),
    eventLoging : require('./eventLoging'),
    community : require('./community'),
    topic : require('./topic'),
    Teams : require('./teams'),
    Player : require('./player'),
    sportVersion : require('./sportVersion'),
    Fixture : require('./Fixture'),
    userFixture : require('./userFixture'),
    notification : require('./notification'),
    Country : require('./country'),
    Competition : require('./competition'),
    userNotification: require('./userNotification'),
    notificationResponse: require('./notificationResponse'),
    sponsorBillboard: require('./sponsorBillboard'),
    fanspickFixture: require('./fanspickFixture'),
    fixturePlayersStatics : require('./fixturePlayersStatics'),
    lkpPosition : require('./lkpPosition'),
    lkpAssociatePosition : require('./lkpAssociatePosition'),
    formations : require('./formations'),
    formationPositionMapping : require('./formationPositionMapping'),
    otp : require('./otps'),
    chatHistory : require('./chatHistory'),
    chatGroups : require('./chatGroups'),
    userContacts : require('./userContacts'),
    additionalCountryData : require('./additionalCountryData'),
    stages : require('./stages'),
    seasons : require('./seasons'),
    lkpstageteams : require('./lkpstageteams'),
    userActionsLogs : require('./userActionsLogs')
};